### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by nopnop2002** [geosmall/UAVCAN-for-STM32-Arduino#1]
I'm very interested in your project.
I'm planning to use STM32F103.
But I see your [STM32F103C8/libcanard_example] folder, and i am confused.

There is two ino file, but it doesn't have setup() & loop().
SystemClock_Config_72MHz.ino
libcanard_example.ino

There is one main.c,it have setup() & loop().
main.c

I compile your code.
I'm using Arduino IDE v1.8.5 with Arduino Core STM32 v1.5.0.
But i got this error.

	sketch\can.c: In function 'MX_CAN_Init':

	can.c:12:12: error: 'CAN_InitTypeDef {aka struct <anonymous>}' has no member named 'SJW'

	   hcan.Init.SJW = CAN_SJW_1TQ;

	            ^

	can.c:13:12: error: 'CAN_InitTypeDef {aka struct <anonymous>}' has no member named 'BS1'

	   hcan.Init.BS1 = CAN_BS1_1TQ;

	            ^

	can.c:14:12: error: 'CAN_InitTypeDef {aka struct <anonymous>}' has no member named 'BS2'

	   hcan.Init.BS2 = CAN_BS2_1TQ;

	            ^

	can.c:15:12: error: 'CAN_InitTypeDef {aka struct <anonymous>}' has no member named 'TTCM'

	   hcan.Init.TTCM = DISABLE;

	            ^

	can.c:16:12: error: 'CAN_InitTypeDef {aka struct <anonymous>}' has no member named 'ABOM'

	   hcan.Init.ABOM = DISABLE;

	            ^

	can.c:17:12: error: 'CAN_InitTypeDef {aka struct <anonymous>}' has no member named 'AWUM'

	   hcan.Init.AWUM = DISABLE;

	            ^

	can.c:18:12: error: 'CAN_InitTypeDef {aka struct <anonymous>}' has no member named 'NART'

	   hcan.Init.NART = DISABLE;

	            ^

	can.c:19:12: error: 'CAN_InitTypeDef {aka struct <anonymous>}' has no member named 'RFLM'

	   hcan.Init.RFLM = DISABLE;

	            ^

	can.c:20:12: error: 'CAN_InitTypeDef {aka struct <anonymous>}' has no member named 'TXFP'

	   hcan.Init.TXFP = DISABLE;

	            ^

	exit status 1
	'CAN_InitTypeDef {aka struct <anonymous>}' has no member named 'SJW'

 
Please tell me a procedure of compilation.

Thank you.

**Comment by geosmall** [comment]
I see you are using Arduino Core STM32 v1.5.0.  In README.md you can see I tested under v1.4.0.  It looks like ST has gone reworked the CAN interface on the HAL version used with v1.5.0, so I recommend you revert to that for now.  I will have to look into changes needed to work with the HAL update.

**Comment by geosmall** [comment]
HAL CAN driver abreviated migration guide (from https://community.st.com/s/question/0D50X00009Xkg2MSAR/stm32f4xx-rework-of-hal-can-driver-examples):

- Fields of CAN_InitTypeDef structure are renamed: SJW to SyncJumpWidth, BS1 to TimeSeg1, BS2 to TimeSeg2, ABOM to AutoBusOff, AWUM to AutoWakeUp, NART to AutoRetransmission (inversed), RFLM to ReceiveFifoLocked and TXFP to TransmitFifoPriority
- HAL_CAN_Init() is split into both HAL_CAN_Init() and HAL_CAN_Start()
- HAL_CAN_Transmit() is replaced by HAL_CAN_AddTxMessage() to place Tx request, then HAL_CAN_GetTxMailboxesFreeLevel() for polling until completion
- HAL_CAN_Transmit_IT() is replaced by HAL_CAN_ActivateNotification() to enable transmission with interrupt mode, then HAL_CAN_AddTxMessage() to place Tx request
- HAL_CAN_Receive() is replaced by HAL_CAN_GetRxFifoFillLevel() for polling until reception, then HAL_CAN_GetRxMessage() to get Rx message
- HAL_CAN_Receive_IT() is replaced by HAL_CAN_ActivateNotification() to enable reception with interrupt mode, then HAL_CAN_GetRxMessage() in the receive callback to get Rx message
- HAL_CAN_Sleep() is renamed to HAL_CAN_RequestSleep()
- HAL_CAN_TxCpltCallback() is split into HAL_CAN_TxMailbox0CompleteCallback(), HAL_CAN_TxMailbox1CompleteCallback() and HAL_CAN_TxMailbox2CompleteCallback()
- HAL_CAN_RxCpltCallback() is split into HAL_CAN_RxFifo0MsgPendingCallback() and HAL_CAN_RxFifo1MsgPendingCallback()

**Comment by nopnop2002** [comment]
Thank you for your reply.
Your project is very valuable.
I hope that your code work with Arduino Core STM32 v1.5.0.

**Comment by geosmall** [comment]
Reopened, updated to work with Arduino_Core_STM32 v1.8.

**Comment by nopnop2002** [comment]
Great!!
I'll try next weekend.

**Comment by geosmall** [comment]
I've now successfully tested on F103 Bluepill (documented here https://www.stm32duino.com/viewtopic.php?p=651#p651).  I still need to test the F303 demo.

**Comment by geosmall** [comment]
UAVCAN functional testing now completed for both F103C8 and F303CC examples.  Repo is now considered updated to be compatible with v1.8 Arduino_Core_STM32.

**Comment by geosmall** [comment]
Testing complete, repo is now considered updated to be compatible with v1.8 Arduino_Core_STM32.
