### ISSUE TITLE
About can.c

### ISSUE THREAD

**Issue by nopnop2002** [geosmall/UAVCAN-for-STM32-Arduino#2]
Hello.

I have two questions.

1.about HAL_CAN_MspInit

This is STM32F103C8/libcanard_example/can.c:

	void HAL_CAN_MspInit(CAN_HandleTypeDef* canHandle)
	{

	  GPIO_InitTypeDef GPIO_InitStruct;
	  if (canHandle->Instance==CAN1) {

	    /* CAN1 clock enable */
	    __HAL_RCC_CAN1_CLK_ENABLE();
	  
	    /**CAN GPIO Configuration    
	    PA11     ------> CAN_RX
	    PA12     ------> CAN_TX 
	    */
	    GPIO_InitStruct.Pin = GPIO_PIN_11;
	    GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
	    GPIO_InitStruct.Pull = GPIO_NOPULL;
	    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

	    GPIO_InitStruct.Pin = GPIO_PIN_12;
	    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
	    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
	    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

	  }

	}

This is STM32F303CC/libcanard_example_F3/can.c:

Why not the same as STM32F103??

-Why is F103 executing HAL_GPIO_Init twice? ?

-Why is F103 CAN1 and F303 CAN? ?

	void HAL_CAN_MspInit(CAN_HandleTypeDef* canHandle)
	{

	  GPIO_InitTypeDef GPIO_InitStruct;
	  if(canHandle->Instance==CAN)
	  {

	    // GPIO Ports Clock Enable
	    __HAL_RCC_GPIOA_CLK_ENABLE();

	    // CAN clock enable
	    __HAL_RCC_CAN1_CLK_ENABLE();
	  
	    // CAN GPIO Configuration    
	    // PA11    ------> CAN_RX
	    // PA12    ------> CAN_TX 
	    GPIO_InitStruct.Pin = GPIO_PIN_11 | GPIO_PIN_12;
	    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
	    GPIO_InitStruct.Pull = GPIO_NOPULL;
	    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
	    GPIO_InitStruct.Alternate = GPIO_AF9_CAN;
	    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
	  }

	}

2.HAL_CAN_MspDeInit

This is STM32F103C8/libcanard_example/can.c:

	void HAL_CAN_MspDeInit(CAN_HandleTypeDef* canHandle)
	{

	  if (canHandle->Instance==CAN1) {
	    // Peripheral clock disable
	    __HAL_RCC_CAN1_CLK_DISABLE();
	  
	    // CAN GPIO Configuration    
	    // PA11     ------> CAN_RX
	    // PA12     ------> CAN_TX 
	    HAL_GPIO_DeInit(GPIOA, GPIO_PIN_11 | GPIO_PIN_12);
	  }

	}

STM32F303CC/libcanard_example_F3/can.c:
I think, PB8/PB9 is incorect.

	void HAL_CAN_MspDeInit(CAN_HandleTypeDef* canHandle)
	{

	  if(canHandle->Instance==CAN)
	  {
	    // Peripheral clock disable
	    __HAL_RCC_CAN1_CLK_DISABLE();
	  
	    // CAN GPIO Configuration    
	    // PB8     ------> CAN_RX
	    // PB9     ------> CAN_TX 
	    HAL_GPIO_DeInit(GPIOB, GPIO_PIN_8|GPIO_PIN_9);
	  }

	}

**Comment by geosmall** [comment]
F1 and F3 have different GPIO implementations, so the init calls are a bit different.  CAN vs CAN1 is another datasheet detail.  ST has a bad habit of minor hw/sw differences across product families. 
 STM32CubeMX tool and associated examples can help you see differences in addition to the datasheets.

You are correct the DeInit function is using wrong pins PB8/9, although the example code never calls DeInit so no impact to functionality of the demo.

**Comment by nopnop2002** [comment]
OK
I understood.

I have one more question.

The node IDs of f103 and f303 are both 10.
Can both communicate? ?

	STM32F103C8\libcanard_example\uavcan.c(101):   canardSetLocalNodeID(&g_canard, 10);
	STM32F303CC\libcanard_example_F3\uavcan.c(101):   canardSetLocalNodeID(&g_canard, 10);

**Comment by geosmall** [comment]
The examples are meant to be standalone slave CAN node examples, so I kept the same ID.  If you want both to co-exist just change the ID number.

I'm going to close this issue, GitHub issues are intehttps://www.stm32duino.com/viewtopic.php?f=10&t=99nded for bug reporting.  For general discussion I recommend here

**Comment by nopnop2002** [comment]
Thank you for your support.
