### ISSUE TITLE
Problem in Compiling

### ISSUE THREAD

**Issue by Vicky-S** [geosmall/UAVCAN-for-STM32-Arduino#3]
Board Used : STM32F103C8

I got the following Error while compiling the example code in arduino.

c:/users/randd/appdata/local/arduino15/packages/stm32/tools/xpack-arm-none-eabi-gcc/9.2.1-1.1/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: sketch\uavcan.c.o: in function `getsetHandleCanard':

uavcan.c:(.text.getsetHandleCanard+0x78): undefined reference to `getParamByName'

collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board Generic STM32F1 series.

**Comment by geosmall** [comment]
Hard to tell with the limited information.  How did you copy/clone the example over?

**Comment by Vicky-S** [comment]
I downloaded the zip file in this repo and unzipped in my desktop and then opened the .ino file.

STM32 Core Version : 1.8
Arduino IDE Version : 1.8.9

**Comment by geosmall** [comment]
I've been able to confirm this issue.  For some reason it links under -Og optimization that I've been using but fails under the default -Os option.  I've added declarations for the GetParam inline functions to uavcan.c and pushed them, it appears to link  fine now.  Can you update you local copy and confirm this fixes your isssue?

**Comment by geosmall** [comment]
No response from OP.  I've been able to duplicate issue, make changes and confirm that issue has been addressed.  Closing this issue.
